CATEGORIES = {'https://scalebay.ru/category/masshtabnye-modeli_otechestvennye-avtomobili': 'Масш-ные мод./Отечественные автомобили',
              'https://scalebay.ru/category/masshtabnye-modeli_zarubezhnye-avtomobili': 'Масш-ные мод./Зарубежные автомобили',
              'https://scalebay.ru/category/masshtabnye-modeli_traktory': 'Масш-ные мод./Тракторы, строительно-дорожная техника',
              'https://scalebay.ru/category/masshtabnye-modeli_raritetnye-i-redkie-modeli': 'Масш-ные мод./Раритетные и редкие модели',
              'https://scalebay.ru/category/masshtabnye-modeli_aviaciya': 'Масш-ные мод./Авиация',
              'https://scalebay.ru/category/masshtabnye-modeli_bronetehnika': 'Масш-ные мод./Бронетехника',
              'https://scalebay.ru/category/sbornye-modeli_motocikly': 'Масш-ные мод./Мотоциклы',
              'https://scalebay.ru/category/masshtabnye-modeli_prochee': 'Масш-ные мод./Прочее',
              'https://scalebay.ru/category/sbornye-modeli_bronetehnika-tanki-btt': 'Сб-ые мод./Киты/Бронетехника, танки (БТТ)',
              'https://scalebay.ru/category/sbornye-modeli_samolety-vertolety-rakety-aviaciya': 'Сб-ые мод./Киты/Самолеты, вертолеты, ракеты (авиация)',
              'https://scalebay.ru/category/sbornye-modeli_korabli-podvodnye-lodki-flot': 'Сб-ые мод./Киты/Корабли, подводные лодки (флот)',
              'https://scalebay.ru/category/sbornye-modeli_pushki-oruzhie-artilleriya': 'Сб-ые мод./Киты/Пушки, оружие (артиллерия)',
              'https://scalebay.ru/category/sbornye-modeli_avtomobili': 'Сб-ые мод./Киты/Автомобили',
              'https://scalebay.ru/category/sbornye-modeli_figury-miniatyury': 'Сб-ые мод./Киты/Фигуры, миниатюры',
              'https://scalebay.ru/category/sbornye-modeli-kity_drugoe': 'Сб-ые мод./Киты/Другое',
              'https://scalebay.ru/category/zhurnalnye-serii_partvorki_traktory-istoriya-lyudi-mashiny-hachette': 'Жур-ные ср./Парт-ки/Тракторы. История, люди, машины (Hachette)',
              'https://scalebay.ru/category/zhurnalnye-serii-partvorki_avtolegendy-sssr-deagostini': 'Жур-ные ср./Парт-ки/Автолегенды СССР (DeAgostini)',
              'https://scalebay.ru/category/zhurnalnye-serii-partvorki_policejskie-mashiny-mira-deagostini': 'Жур-ные ср./Парт-ки/Полицейские машины мира (DeAgostini)',
              'https://scalebay.ru/category/zhurnalnye-serii-partvorki_gaz-m20-pobeda-v-masshtabe-18-deagostini': 'Жур-ные ср./Парт-ки/ГАЗ-М20 Победа в масштабе 1:8 (DeAgostini)',
              'https://scalebay.ru/category/zhurnalnye-serii-partvorki_ferrari-collection-gefabbri': 'Жур-ные ср./Парт-ки/Ferrari Collection (GeFabbri)',
              'https://scalebay.ru/category/zhurnalnye-serii-partvorki_avtomobil-na-sluzhbe-deagostini': 'Жур-ные ср./Парт-ки/Автомобиль на службе (DeAgostini)',
              'https://scalebay.ru/category/zhurnalnye-serii-partvorki_superkary-deagostini': 'Жур-ные ср./Парт-ки/Суперкары (DeAgostini)',
              'https://scalebay.ru/category/zhurnalnye-serii-partvorki_kultowe-auta-prl-u-polsha': 'Жур-ные ср./Парт-ки/Kultowe Auta PRL-u (Польша)',
              'https://scalebay.ru/category/zhurnalnye-serii-partvorki_russkie-tanki-gefabbri-172': 'Жур-ные ср./Парт-ки/Русские танки (GeFabbri) 1:72',
              'https://scalebay.ru/category/zhurnalnye-serii-partvorki_tanki-mira-172': 'Жур-ные ср./Парт-ки/Танки Мира 1:72',
              'https://scalebay.ru/category/zhurnalnye-serii-partvorki_boevye-mashiny-mira-172-eaglemoss-collections': 'Жур-ные ср./Парт-ки/Боевые машины мира 1:72 (Eaglemoss collections)',
              'https://scalebay.ru/category/zhurnalnye-serii-partvorki_the-james-bond-car-collection-avtomobili-dzhejmsa-bonda': 'Жур-ные ср./Парт-ки/The James Bond Car Collection (Автомобили Джеймса Бонда)',
              'https://scalebay.ru/category/zhurnalnye-serii-partvorki_nasekomye-i-ih-znakomye-deagostini': 'Жур-ные ср./Парт-ки/Насекомые и их знакомые (DeAgostini)',
              'https://scalebay.ru/category/zhurnalnye-serii-partvorki_drugie-serii': 'Жур-ные ср./Парт-ки/Другие серии',
              'https://scalebay.ru/category/fototravlenie-dekali-kraski-materialy': 'Фототр-ние, декали, краски, материалы ',
              'https://scalebay.ru/category/figurki': 'Фигурки',
              'https://scalebay.ru/category/elementy-dlya-dioram': 'Элементы для диорам (объекты, материалы)',
              'https://scalebay.ru/category/zheleznodorozhnye-modeli': 'Железндр. модели',
              'https://scalebay.ru/category/boksy-korobki-stellazhi-podstavki': 'Боксы, коробки, стеллажи, подставки',
              'https://scalebay.ru/category/masshtabnye-modeli_detali-zapchasti-komplektuyushie': 'Детали, запчасти, комплектующие',
              'https://scalebay.ru/category/instrumenty-rashodnye-materialy': 'Инстр., расход. матер.',
              'https://scalebay.ru/category/radioupravlyaemye-modeli': 'Радиоупр. модели',
              'https://scalebay.ru/category/literatura-po-modelizmu': 'Литература, каталоги, журналы',
              'https://scalebay.ru/category/masshtabnye-modeli_drugoe': 'Другое'}
