ALL_MANUFACTURERS = {'128', '12ART-FINE-MODEL-CARS', '3D Karton', '3DF Express', '3DM', '50CC Legends', '78art',
                     'AA Models', 'Aber', 'Abordage', 'Abrex', 'Absolute Hot', 'Abteilung502', 'Academy', 'ACE',
                     'AD-Modum', 'Advanced Modeling', 'Aeroclub', 'AFV club', 'AGM', 'AHC Models', 'AIM Fan Model',
                     'Aires', 'AirFix', 'AJ Model', 'AK Interactive', 'AKhobby', 'Alan', 'Alanger', 'ALARME',
                     'Alclad II', 'ALERTE', 'Alex Miniatures', 'Alezan', 'ALF', 'ALFAMODEL-43', 'Almost Real', 'ALR',
                     'Altaya', 'Amalgam', 'Amercom', 'American Diorama', 'American Heritage Models', 'AMG Models',
                     'Amigo Models', 'AMK', 'AML', 'AMMO MIG', 'Amodel', 'A-Model', 'Amour', 'AMP', 'AMR', 'AMT',
                     'Amusing Hobby', 'Anson', 'Answer', 'AnyMe', 'Aoshima (DISM)', 'Apex Racing', 'Applywood workshop',
                     'ARK models', 'ARM.PNT', 'Arma Models', 'Armada Hobby', 'ArmaHobby', 'ArModel', 'ARMOR35',
                     'Armory', 'Armour Collection', 'ARS Model', 'Art Model', 'ART-model', 'Ascensio', 'ASK Models',
                     'ASQ', 'AT Collections', 'ATC', 'Athearn', 'Atlantic', 'Atlas', 'Audi Museum', 'Auhagen',
                     'Aurora Hobby', 'Authentic Decals', 'Auto Pilen', 'Auto World', 'AutoArt', 'Autobahn / Bauer',
                     'autocult', 'Autodrive', 'AUTOMAXX', 'Automodelle AMW', 'Automodello', 'Autotime / Autogrand',
                     'Avanstyle (Frontiart)', 'Avart Arhive', 'AVD Models', 'AVD дополнения', 'AVD покрышки', 'Avis',
                     'AWM', 'AZModel', 'Azur', 'Bachmann', 'Balaton Modell', 'Bang', 'Bare-Metal Foil Co.', 'Bauer',
                     'Baumi', 'BBR', 'Bburago', 'Begemot', 'BeKa', 'Best Model', 'Best of Show', 'Betexa', 'Biante',
                     'Bing', 'BisonDecals', 'Bizarre', 'black dog', 'BlackBox', 'Blu Tack', 'Blue Rider',
                     'BM Creations', 'BM-Toys', 'Bobcat', 'Bobcat dealer', 'Boley', 'Border Model', 'BOX-MODEL',
                     'Bravo-6', 'Brekina', 'Brengun', 'BRITAINS', 'Bronco', 'Brooklin Models', 'Bruder', 'Brumm',
                     'Brumos', 'BS Design', 'Busch', 'by AK', 'By Volk', 'Caesar miniatures', 'CAL', 'Capitan',
                     'Car Badge', 'Cararama / Hongwell', 'Carline', 'CarNel', 'CAROUSEL', 'Cartima', 'Cartrix',
                     'CBModels', 'Celero', 'Centauria', 'Century', 'Century Dragon', 'Century Wings', 'CHAMAELEON',
                     'CHIEFF Models', 'China Models', 'CHROMES', 'CHRONO', 'Classic 43', 'Classic Carlectables',
                     'Classicbus', 'Classy Hobby', 'CLC Models', 'ClearProp', 'CM Model', 'CMC', 'CMD', 'CMF', 'CMK',
                     'CMR', 'CMW Classic Metal Works', 'Colibri Decals', "Collector's Classics", 'CON-COR', 'Condor',
                     'Conrad', 'Copper State Models', 'Corgi', 'Corsar Rex', 'Crazy Classic Team', 'CrazyHands',
                     'Creative Masters', 'Crown Premiums', 'Cult Scale Models', 'Cursor', 'Cutting Edge Modelworks',
                     'CYBER HOBBY', 'D.N.K.', 'Daffi', 'DANmodels', 'Dark Dream Studio', 'Darkside', 'Das Werk',
                     'DasModel', 'DAYdiecastETCH', 'DCM', 'DCN Model', 'DD-MODELS', 'DeAgostini', 'Decal Shop',
                     'DECOOL', 'Del Prado', 'DeMauri', 'Demprice', 'DenisssModels', 'DetailCars', 'DiamondLabel',
                     'Diapet', 'Dickie Spielzeug', 'Die-cast at home', 'Die-Cast super', 'DieCastTeam',
                     'Different Scales', 'Dinky Toys', 'DiOlex Production', 'Diopark', 'DioramaTech', 'DiP Models',
                     'Direkt Collections', 'Distler', 'DMA Hue Studio', 'DM-MODELS', 'DNA', 'Doctor Decal', 'Dong Guan',
                     'Dora Wings', 'Dorlop', 'Dragon', 'DSPIAE', 'Dugu', 'Dukase', 'DUPLI COLOR', 'DVC', 'DZD',
                     'Eaglemoss', 'Easy Model', 'Ebbro', 'Eco-Wood-Art', 'Edison Giocattoli', 'Edmon Studio', 'Eduard',
                     'Efsi Toys', 'Eidolon Make-Up', 'ELF', 'Eligor', 'Eman', 'Emboss', 'EMC Models', 'Emek', 'ENGUP',
                     'ERA', 'ERTL', 'ESCI', 'Espewe Modelle', 'Esval Models', 'EUREKA XXL', 'EuroModell',
                     'Evergreen (USA)', 'Evolution Miniatures', 'EVRAT', 'EVR-mini', 'EWA', 'Excel', 'Exoto',
                     'EXPRESSO WINGS', 'EXTRA MODEL', 'Extratech', 'Falcon Models', 'Faller', 'Fantasy Warrior',
                     'Fazo_lab', 'Feelin_3d', 'Fengda', 'Figuma', 'Figutec', 'Fine Molds', 'FinMilModels',
                     'First 43 Models', 'First Response', 'First to Fight', 'FLAGMAN', 'Fly', 'Fly Car Model',
                     'FlyHawk Model', 'Forces of Valor', 'Fore Hobby', 'Format72', 'Forward-68', 'Foxtoys',
                     'Franklin Mint', 'FRANSTYLE', 'Franzis', 'Freedom Models', 'Friulmodel', 'From Japan', 'Frontiart',
                     'FUGU_GARAGE', 'Fujimi Mokei', 'Fury Models', 'Gaffe', 'GAMA', 'Garage', 'Garbuz models', 'Gartex',
                     'Gaso.Line', 'GCD', 'GE Models', 'Gearbox', 'Gecko-Models', 'GeminiJets', 'Gems & Cobwebs',
                     'GENUINE FORD PARTS', 'GFCC', 'GIM', 'Ginaf', 'GK Racer Series', 'Glencoe models', 'GLM',
                     'GMP / ACME', 'GMU Model', 'Gold Medal Models', 'Golden Wheel Models', 'Goldvarg', 'GolubModels',
                     'GoNzA', 'Gorky Models', 'GP Replicas', 'GPM', 'Great Wall Hobby', 'Green Stuff World',
                     'Greenlight', 'Grell Werbemittel', 'Gremlin Models', 'Griffon', 'Group Masters', 'GT Autos',
                     'GT Spirit', 'GTI Collection', 'Guiloy', 'Guisval', 'GunTower Models', 'Hachette', 'HADmodels',
                     'Halinski', 'Harder_Steenbeck', 'Hartoy Inc.', 'Hasbro', 'Hasegawa', 'Hat Plastic Models',
                     'Hauler', 'HC Models', 'Heavy Hobby', 'HECO Modeles', 'HedgeModels', 'Heki', 'Heller', 'Herpa',
                     'High Speed', 'Highway 61', 'Historic', 'Hi-Story', 'HK Models', 'Hobby 2000', 'Hobby Boss',
                     'Hobby Design', 'Hobby Fan', 'HOBBY GEAR', 'Hobby I Work', 'Hobby Master', 'Hobby Model',
                     'Hobby Planet', 'HobbyCraft', 'Holland Oto', 'Homer', 'Hot Wheels', 'Hot Wheels Elite', 'HPI',
                     'HRN-Models', 'Humbrol', 'I Love Kit', 'IBG Models', 'ICM', 'ICONIC-REPLICA', 'ICV (СПб)',
                     'IGNITION-MODEL', 'IGRA', 'Ilario', 'ING SmallCarArt', 'Inno Models', 'Interus', 'IOM-KIT',
                     'i-Scale', 'IST', 'ISTPlus', 'Italeri', 'IVY', 'IXO', 'JACO', 'Jada Toys', 'JADAR', 'Jadi',
                     'Jaegerndorfer Collection', 'Jaguar Models', 'JAS', 'JB Modellautos', 'J-Collection',
                     'Jewel Cases', 'JF Creations', 'Jim Scale', 'JKM', 'Joal', 'John Day Models', 'Johnny Lightning',
                     'Jolly Model', 'Jouef Evolution', 'Joy City', 'JTK', 'K_S Precision Metals', 'Kaden', 'Kajika',
                     'Kamaz Master', 'Kangnam', 'Kartonowa Kolekcja', 'Kato', 'Kaupang Miniatures', 'KAV models', 'KDW',
                     'Kempal', 'KengFai', 'KEPmodels', 'KESS Model', 'Kibri', 'KievModel HO', 'Kilo Works', 'Kinetic',
                     'King star', 'Kinsmart', 'Kitech', 'Kitty Hawk', 'KK Scale', 'kkav-kits', 'K-Model', 'Kondor',
                     'Konoos', 'KORA', 'Korean models', 'KOVAP', 'Kovozavody Prostejov', 'KP Models', 'Kraft Lab',
                     'Kremlin Vehicle park', 'Kuivalainen', 'KV Decol', 'KV Models', 'Kyosho', 'La Mini Miniera',
                     'Lada Image', 'Lancer', 'Lang Feng Model', 'Laser Hobby', 'Lastochka', 'Laudoracing-Models',
                     'LCD MODELS', 'Le Mans Miniatures', 'Leadwarrior', 'Legends of Racing', 'LEGO', 'LenmodeL',
                     'Leo Models', 'Lev Resin', 'LeX models', 'LIFE in SCALE', 'Life Miniatures', 'LifeColor',
                     'LionRoar', 'Lion-Toys', 'Little dump', 'LiveResin', 'Lledo', 'L-Model', 'Looksmart',
                     'Louis Surber', 'LP Models', 'LS Collectibles', 'LSModel', 'Lucky Diecast', 'Lucky Models',
                     'Lucky Plan', 'Luppa', 'LUSO-toys', 'Luxcar', 'LUXCASE', 'Luxury Collectibles', 'Luxury die-cast',
                     'M2 Machines', 'M4', 'MAC Distribution', 'Macadam', 'MACHETE', 'Made in GDR', 'Magic Models',
                     'Maisto', 'Majorette', 'Make Up', 'MAKSIPROF', 'ManWah', 'Maquette', 'MARK43', 'Marklin', 'MARS',
                     'Mars Models', 'Marsh Models', 'MARTIN', 'Maserati Models', 'MASTER', 'Master Box',
                     'Master Diecast', 'MASTER KORABEL', 'Master Model', 'Master Tools', 'Mastercast', 'MasterClub',
                     'MasterCraft', 'Matchbox', 'Matrix', 'Mattel', 'Maxi Car', 'MAXI COLOR', 'Maxichamps',
                     'Maxima Scale', 'MaxModels', 'Max-Models', 'MBH Models', 'MCW', 'MD-models', 'Meng', 'Mercury',
                     'Merit', 'Metallic Details', 'Metro', 'Micro Scale Design', 'MIG productions', 'MIL Customs',
                     'Milestone Miniatures', 'MilitaryWheels', 'Mini GT', 'MINI HELMET', 'MINI MAN', 'Minialuxe',
                     'Miniarm', 'MiniArt', 'Miniaturmodelle', 'Minibase', 'Minichamps', 'MiniClassic', 'Minicraft',
                     'MiniCraft Scale Models', 'MiniHobbyModels', 'MINIPARTES', 'MiniTank', 'MiniWarPaint', 'MIRA',
                     'Mirage Hobby', 'Mirror-models', 'MISTERCRAFT', 'Mitica', 'MixAuto', 'MK Modelle', 'MK models',
                     'MK-MINIATURES', 'MMP', 'Model Box', 'Model Depo', 'Model Point', 'ModelCarGroup', 'Modelcollect',
                     'Modeler', 'ModelGun', 'Model-Icons', 'modelk', 'ModellingMaster', 'ModelLux', 'ModelPro',
                     'ModelSvit', 'Modimio', 'MODUS 90', 'Moebius Models', 'Molotow', 'Mondo Motors', 'Mondsee',
                     'Monogram', 'Montana', 'MONTI SYSTEM', 'Moon', 'Morem', 'Morrison', 'MosKit', 'Mot Hobby', 'Motip',
                     'Motor Max', 'Motorama', 'Motorart', 'Motorhead', 'MOTORHELIX', 'MotoScaleModels', 'MPC', 'MPM',
                     'MR Collection', 'Mr.Hobby', 'MR-MODELS', 'M-Smart', 'MTech (M4)', 'MXpression', 'Nacoral S.A.',
                     'NEO', 'Neomega', 'New Penguin', 'New Ray', 'NH Detail', 'Nickel', 'Nik-Models', 'Nitto', 'NMD',
                     'Noch', 'noname', 'Norev', 'Norscot', 'NorthStar Models', 'Nostalgie', 'NVA', 'NZG Modelle',
                     'Odeon', 'OFFICINA-942', 'OKB Grigorov', 'Old Cars', 'Old Garage', 'OLDCARS', 'OLFA',
                     'Olimp Models', 'Olm Design', 'One by One Production', 'ONYX', 'Opus studio', 'Orion',
                     'ORNST model', 'Otto Mobile', 'Ovs-Decals', 'Oxford', 'Pacific88', 'Palma43', 'Panda Hobby',
                     'PANTHEON', 'PanzerKampf', 'Panzerstahl', 'Paragon', 'Part', 'PasDecals', 'PasModels',
                     'Paudi Models', 'Pavla Models', 'PB Scale Models', 'PEAKO', 'Pegas-Models', 'Pegasus Hobbies',
                     'Pego', 'PERFEX', 'Permot', 'Phoenix Mint', 'Piko', 'PinKo', 'Planet models', 'Platz', 'Plusmodel',
                     'PMS', 'Pocher', 'Polistil', 'POPRace', 'Porsche Museum', 'PosterCars', 'Potato Car', 'Praline',
                     'Precision Miniatures', 'Preiser', 'Premium ClassiXXs', 'Premium Collectibles',
                     'Premium Scale Models', 'PremiumX', 'Print Scale', 'ProDecals', 'Progetto K', 'Prommodel43',
                     'Prop&Jet', 'Propagteam', 'Provence Moulage', 'PST', 'Pt Models', 'Quartzo', 'Quickboost',
                     'Quinta Studio', 'Quiralu', 'R.A.M.I.', 'R.V. AIRCRAFT', 'Racing Champions inc.',
                     'Rare Car Models', 'RARESIN', 'RAROG', 'Rastar', 'RB Model', 'RB productions', 'RBA Collectibles',
                     'Rebel Custom', 'Record - M.R.F.', 'Red Box', 'Red Iron Models', 'Red Line', 'RE-EL TOYS',
                     'Renn Miniatures', 'Renner Werbemittel', 'Replicars', 'ResKit', 'Rest Models', 'RETRO LINE',
                     'Retro Wings', 'Revaro', 'Revell', 'Rextoys', 'REXx', 'Ricko', 'Rietze', 'Riich Models', 'RIO',
                     'River Point', 'RMZ Hobby', 'RO MODELS', 'Road Champs', 'Road Kings', 'Rob-Taurus', 'Roco',
                     'RODA models', 'Roden', 'ROS', 'Roskopf', 'Rosso', 'Rosso & Fly', 'Roubloff', 'RPG-model', 'RPM',
                     'RS Models', 'RTM', 'Ruppert Kopp', 'RusAir', 'Russian collection', 'Rye Field Model', 'S_B',
                     'SABRE', 'SabreKits', 'Saico', 'Sarmat Resin', 'SBS Model', 'SC Johnson (USA)', 'Scale 48',
                     'Scale For Soul', 'scale_work', 'ScaleGarage', 'ScaleMasters', 'Schabak', 'Schuco', 'SE Modell',
                     'Seal Model Kit', 'SEAT', 'SES Automodelle', 'SG-Modelling', 'Shelby Collectibles', 'Shuriken',
                     'Signature', 'SIKU', 'SILAS', 'SIO Models', 'SJO', 'Skale Wings', 'SKIF', 'Sky-High', 'Smer',
                     'SMM', 'S-Model', 'SnakeModel', 'Sochi 2014', 'Solido', 'Sonstige', 'SophiArt', 'South Front',
                     'SOVA-M', 'Soviet Armour', 'Spark', 'SpAsov', 'Special Hobby', 'Stalingrad', 'Starline',
                     'Start Scale Models', 'STC', 'STC START', 'STM', 'Storm Factory', 'Studio Perfect Model',
                     'Sullen-Modelist', 'Sunnyside', 'Sunstar', 'Sunyork Model', 'Super A', 'Suyata', 'Sword', 'SX-Art',
                     'T.R.L. Model', 'Takom', 'Tameo KITs', 'Tamiya (J)', 'TANMODEL', 'Tarangus', 'Tarmac', 'TAYUMO',
                     'Team Caliber', 'Tech3', 'Techart', 'Tecnomodel', 'Tekno', 'Temp models', 'Tesla', 'Testors',
                     'Thunder Model', 'Tic Toc', 'Tiger Model', 'TimeMicro', 'Tin Wizard', "Tins' Toys", 'Tiny Toys',
                     'Tippco', 'T-Model', 'TMTmodels', 'TOGA', 'Tomica', 'Tonkin Replicas', 'Top Marques', 'Top Model',
                     'TOP10', 'TopSpeed', 'Touring', 'Toxso Model', 'ToyWays', 'Trax', 'Triple 9', 'Tristar', 'Trofeu',
                     'Trux', 'TSM Model', 'UCC Coffee', 'Ultimate Diecast', 'ULTRA models', 'UM Military Technics',
                     'UM43', 'UMI', 'Unimax', 'Unique Replicas', 'Universal Hobbies', 'unoMAG', 'UpRise', 'UStar',
                     'UT Models', 'V.V.M / V.M.M.', 'V43', 'Vallejo', 'vanamingo-nn', 'Vanbo', 'Vanguards', 'VAPS',
                     'Vector', 'Vector-Models', 'VeeHobby', 'Verem', 'Very Fire', 'Vespid Models',
                     'VETRINA DISPLAY BOX', 'Victoria', 'Vintage Motor Brands', 'VIP Scale Models', 'VIPcar', 'Vitesse',
                     'Vixen', 'VM models', 'VMB-MODELS', 'VMmodels', 'Vmodels', 'VOIIO', 'Vollmer', 'VoyagerModel',
                     'Vrudik', 'W.M.C. Models', 'War Master', 'Warhammer', 'Wasan', 'Waterloo', 'Weise', 'Welly', 'WEM',
                     'WEMI Models', 'Werk83', 'Western Models', 'White Box', 'White Rose', 'Wiking', 'Wilder', 'Wingsy',
                     'WinModels', 'WIX Collectibles', 'WM KIT', 'W-model', 'Wood Hunter', 'Woodland Scenics', 'WSI',
                     'XcarToys', 'XiaoGuang Model', 'XQ', 'Xuntong Model', 'YAN Model', 'Yat Ming', 'YVS-Models',
                     'Zack Atak', 'Zebrano', 'Zedval', 'Zimi Model', 'Zip-maket', 'ZISS', 'Z-Models', 'ZZ Modell',
                     'аRтБаZа', 'АБ-Моделс', 'Авто-бюро', 'Автоистория (АИСТ)', 'Автомодель 43', 'Автопанорама',
                     'Автопарк', 'АГАТ', 'Адам Жуковский', 'АиФ', 'Акан', 'Аксессуары для диорам', 'Альтаир ИГРУШКИ',
                     'АМформа', 'Антонюк', 'артель Универсалъ', 'Ателье Etch models', 'АтомБур', 'Беркут', 'Бригадир',
                     'Витязь', 'ВМТД', 'Военная летопись', 'Войны и битвы', 'Волжский инструмент', 'Восточный экспресс',
                     'ВЭС (Воронеж)', 'Гараж на столе', 'ГРАНЬ', 'Грузы в кузов', 'Декали Boss', 'Декали ModelLux',
                     'Декали SF-Auto', 'Дилерские модели БЕЛАЗ', 'Другой', 'ЕКБ-models', 'Звезда', 'Империалъ',
                     'Казанская лаборатория', 'КАМОРКА', 'Кар Слайд', 'Киммерия', 'КОБРА', 'КолхоZZ Division',
                     'Комбриг', 'Компаньон', 'Латунный мастер', 'Литература (книги)', 'ЛОМО-АВМ', 'Мажор Моделс',
                     'мастер Dimscale', 'мастер Войтович', 'Мастер Дровишкин', 'Мастер Захаров', 'мастер Колёсов',
                     'мастер Лепендин', 'Мастер Роганов', 'Мастер Скаляров', 'МастерПигмент', 'Мастерская Decord',
                     'Мастерская Fm_Lab', 'мастерская JR', 'Мастерская SEC', 'Мастерская АВТОДОР', 'Мастерская ГоСТ',
                     'Мастерская Знак', 'Мастерская КИТ', 'Мастерская МЕЛ', 'Мастерская РИГА', 'Мастерская СКЕЙЛ',
                     'Маэстро-моделс', 'Мелкосерийка 43', 'Микродизайн', 'МикроМир', 'Миниград', 'Минимир',
                     'Мир Моделей', 'Модел.лаб', 'МОДЕЛИСТ', 'Моделстрой', 'Модель-Сервис', 'Модельхимпродукт',
                     'Моя модель', 'МР СТУДИЯ', 'Наш Автопром', 'Наш масштаб', 'Наши Грузовики', 'Наши Танки', 'Огонек',
                     'ОтВинта', 'ПАО КАМАЗ', 'Петроградъ', 'Петроградъ и S_B', 'Пламенный мотор', 'Планета Патворков',
                     'Победа', 'Прапор', 'Престиж Коллекция', 'Промтрактор', 'ПТВ Сибирь', 'ПУЗЫРЁВЪ', 'РетроЛаб',
                     'Русская миниатюра', 'Ручная работа', 'САИС', 'Сарлаб', 'СВ-Модель', 'Сделано в СССР', 'Сергеев',
                     'Сибртех', 'СМУ-23.S', 'Советский Автобус (СОВА)', 'Солдатики', 'СоюзМакет', 'СПБМ', 'СТАРТ 43',
                     'Студия КАН', 'Студия Колесо', 'Студия МАЛ', 'Студия Офицер', 'Танкоград', 'ТАРАН', 'Темэкс',
                     'Технолог', 'ТехноПарк', 'Три А Студио', 'Три Богатыря', 'Трубач', 'ТРЭКС', 'Уральский Сокол',
                     'Фарфоровая Мануфактура', 'Финоко', 'Хася Моделист', 'Херсон-Моделс', 'Цейхгауз', 'ЧЕТРА',
                     'Э.В.М.', 'Экипаж', 'Элекон', 'Эскадра', 'Юный коллекционер'}




